import { readFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { ProjectStore } from "./project-store.js";
import type { MemoryStore } from "./memory-store.js";
import { atomicWriteFile, getLastNSections } from "./io.js";

export interface CrossProjectInsight {
  project: string;
  category?: string;
  source?: string;
  path?: string;
  snippet: string;
}

export class ContextSync {
  constructor(
    private dataDir: string,
    private localContextFilename: string,
    private localContextEnabled: boolean,
    private projectStore: ProjectStore,
    private memoryStore: MemoryStore,
  ) {}

  /**
   * Gather cross-project insights using semantic search.
   * Uses the project's currentFocus as the query,
   * then searches ALL project memories, excluding the project itself.
   */
  async getCrossProjectContext(
    projectId: string,
    limit = 3,
  ): Promise<CrossProjectInsight[]> {
    const summary = await this.projectStore.getProjectSummary(projectId);
    if (!summary) return [];

    const query = summary.currentFocus || summary.oneLiner;
    if (!query.trim()) return [];

    const allResults = await this.memoryStore.recallMemories(query, undefined, limit * 3);

    return allResults
      .filter(
        (r) =>
          r.project !== projectId &&
          (r.category === "decision" || r.category === "learning" || r.source !== undefined),
      )
      .slice(0, limit);
  }

  /**
   * Write a .cortex.md into the project's actual directory.
   */
  async syncLocalContext(projectId: string): Promise<string | null> {
    if (!this.localContextEnabled) return null;

    const index = await this.projectStore.getIndex();
    const proj = index.projects.find((p) => p.id === projectId);
    if (!proj || !existsSync(proj.path)) return null;

    const summary = await this.projectStore.getProjectSummary(projectId);
    const status = await this.projectStore.getProjectStatus(projectId);

    const projectDir = join(this.dataDir, "projects", projectId);

    // Gather recent knowledge
    const knowledgeDir = join(projectDir, "knowledge");
    let recentDecisions = "";
    let recentLearnings = "";
    if (existsSync(knowledgeDir)) {
      const decisionsPath = join(knowledgeDir, "decisions.md");
      const learningsPath = join(knowledgeDir, "learnings.md");
      if (existsSync(decisionsPath)) {
        const content = await readFile(decisionsPath, "utf-8");
        recentDecisions = getLastNSections(content, 5);
      }
      if (existsSync(learningsPath)) {
        const content = await readFile(learningsPath, "utf-8");
        recentLearnings = getLastNSections(content, 5);
      }
    }

    // Get last 3 session logs
    const sessionsDir = join(projectDir, "sessions");
    let recentSessions = "";
    if (existsSync(sessionsDir)) {
      const files = (await readdir(sessionsDir))
        .filter((f) => f.endsWith(".md"))
        .sort()
        .slice(-3);
      for (const file of files) {
        const content = await readFile(join(sessionsDir, file), "utf-8");
        recentSessions += content + "\n---\n\n";
      }
    }

    // Build the local context document
    let md = `<!-- Auto-generated by Cortex. Do not edit manually. -->\n`;
    md += `<!-- Last synced: ${new Date().toISOString()} -->\n\n`;
    md += `# ${proj.name} — Cortex Context\n\n`;

    if (summary) {
      md += `## Overview\n\n`;
      md += `${summary.oneLiner}\n\n`;
      md += `- **Tech**: ${summary.techStack.join(", ")}\n`;
      md += `- **Modules**: ${summary.modules.join(", ")}\n`;
      md += `- **Current Focus**: ${summary.currentFocus}\n\n`;
    }

    if (summary?.lastSession) {
      md += `## Current Status\n\n`;
      md += `Last session: ${summary.lastSession.date}\n\n`;
      md += `${summary.lastSession.summary}\n\n`;
      if (summary.lastSession.nextTasks.length > 0) {
        md += `### Next Tasks\n\n`;
        for (const t of summary.lastSession.nextTasks) {
          md += `- [ ] ${t}\n`;
        }
        md += "\n";
      }
    }

    if (status) {
      md += `## Detailed Status\n\n${status}\n\n`;
    }

    if (recentDecisions) {
      md += `## Recent Decisions\n\n${recentDecisions}\n`;
    }

    if (recentLearnings) {
      md += `## Recent Learnings\n\n${recentLearnings}\n`;
    }

    if (recentSessions) {
      md += `## Recent Sessions\n\n${recentSessions}`;
    }

    // Cross-Project Context section
    const crossInsights = await this.getCrossProjectContext(projectId);
    if (crossInsights.length > 0) {
      md += `## Cross-Project Context\n\n`;
      for (const insight of crossInsights) {
        const label = insight.source
          ? `${insight.project}/${insight.source}`
          : `${insight.project}/${insight.category ?? "unknown"}`;
        md += `- **[${label}]** ${insight.snippet.slice(0, 200)}\n`;
      }
      md += "\n";
    }

    const localPath = join(proj.path, this.localContextFilename);
    await atomicWriteFile(localPath, md);
    return localPath;
  }
}
